# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
            ],
        ),
    ]
