# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='SOME STRING', max_length=200),
        ),
    ]
